### ISSUE TITLE
Gulp-plumber

### ISSUE THREAD

**Issue by Tudes** [vigetlabs/blendid#171]
I was wondering why you're not using gulp-plumber for sass compiling 

```
.pipe(plumber())
```

instead of the

```
.on('error', handleErrors)
```

Gulp-plumber prevents the pipe from breaking when errors occur. It is efficient at pointing out the errors as well.

**Comment by greypants** [comment]
I implemented that error handling a long time ago before I stumbled upon `gulp-plumber`. It also prevents the pipe from breaking when errors occur, and I it lets me format errors however I want—I log them to the console, and send them to `gulp-notify`. It's been working for me, so I never looked into replacing it. 

Is there something gulp-plumber's doing better? I'm open to improvements.

**Comment by mikeerickson** [comment]
@greypants I have used gulp-plumber in the past, but I found that I actually would rather know about errors, thus the second approach (habdleErrors) was preferred.

**Comment by Hagith** [comment]
Sass errors was sometimes breaking the pipe for me with current approach.
I used your handleErrors function through plumber which solved the problem:

```javascript
.pipe(plumber({
  errorHandler: handleErrors
}))
```

**Comment by greypants** [comment]
This hasn't come up again in the past two years... closing for now.
