### ISSUE TITLE
Publishing app.js/shared.js as well as/instead of using hot middleware

### ISSUE THREAD

**Issue by joeswann** [vigetlabs/blendid#293]
I've got this working nicely for a rails project (it's actually in an engine) - once I realised what hot middleware actually does (until now my setup was a heavily modified version of your old browserify setup from ages ago). 

This is great for developing/livereloading, but I would also like to be able to preview the site (eg show a client) without the 3000 port and browsersync running. I can't just run production to produce js as then I need to also run rails in production mode.

It doesn't matter if app/share only updates when gulp first runs and then middleware takes over, or if it produces files and also shares over middleware.

Have looked at `lib/webpack-multi-config.js` but am still too newb to tell if that `if('development')` block is stopping the files from exporting. Really hate asking for help in an issue but - kinda stuck!

**Comment by joeswann** [comment]
Incase anyone finds this with a similar issue, I've solved this for now by creating a `webpackStaging.js` that just runs `gulp webpack:staging` without any of the env based stuff in `webpack-multi-config`.

**Comment by fedeisas** [comment]
Hi @joeswann! I'm having a similar problem. Do you mind sharing your `webpackStaging.js` file so I can take a look at your approach? I'm really new to webpack :-)
Thanks!

**Comment by joeswann** [comment]
Ahh - sure, it's mainly the production mode with find and replace. I haven't implemented anything 'staging' in `webpack-multi-config`, but it could be used to do staging related tasks.

Update on the above, after a bit more digging,  this seems is just how `HotModuleReplacementPlugin` works, as it replaces the files with the event stream. 

I guess ideally it would just run `gulp webpack:staging` when exiting gulp, that way whenever you finish developing it would make sure there was an up to date version of those files. Not sure if there are any 'on exit' hooks in gulp, though. Not my area of expertise!

```
var config = require('../config')
if(!config.tasks.js) return

var config  = require('../lib/webpack-multi-config')('staging')
var gulp    = require('gulp')
var logger  = require('../lib/compileLogger')
var webpack = require('webpack')

var webpackStagingTask = function(callback) {
  webpack(config, function(err, stats) {
    logger(err, stats)
    callback()
  })
}

gulp.task('webpack:staging', webpackStagingTask)
module.exports = webpackStagingTask
```

**Comment by johanneslamers** [comment]
Yes would love to have this as an option.

**Comment by scottbaggett** [comment]
+1

**Comment by greypants** [comment]
Closing in favor of https://github.com/vigetlabs/blendid/issues/428

Though you now get full webpack access in blendid, and could do whatever env checks and manipulation you wanted to in the [`customizeWebpackConfig`](https://github.com/vigetlabs/blendid#customizeWebpackConfig) callback option.
