### ISSUE TITLE
Adding an audio file

### ISSUE THREAD

**Issue by interglobalmedia** [vigetlabs/blendid#315]
Hi:

I want to add an audio file to my project. I tried to add an audio folder to my src folder and do it that way, but it did not work. What would be the correct way to add one? Please advise. Thanks!

**Comment by greypants** [comment]
Just follow the same pattern as the fonts task. Duplicate the task, update the name and paths, then add the task name to this array: https://github.com/vigetlabs/gulp-starter/blob/master/gulpfile.js/lib/getEnabledTasks.js#L5

I should make that easier...

**Comment by interglobalmedia** [comment]
Thanks Dan! I'll try it out now.

**Comment by greypants** [comment]
See #350
