### ISSUE TITLE
Rails can't find js files in development mode?

### ISSUE THREAD

**Issue by davidham** [vigetlabs/blendid#330]
I'm adding your splendid gulp-starter to my Rails app. I added the files from `extras/rails` to the appropriate places, but I can't figure out how to get the javascript to work. Here's what I did:
- I replaced the 'server' in config.json with `"proxy": "http://localhost:3000"`(that's where Rails serves
- I added `<script src="<%= gulp_js_path 'app.js'%>"></script>` to my `layouts/application.html.erb`

But when I view a Rails page, it renders the javascript tag like: `<script src="/public/javascripts/app.js"></script>`, and I get a 404. I know Webpack is doing some magic to insert that into the page, but how do I get it to work in a Rails context?

Thanks so much--I used an earlier version of gulp-starter and I love where you're taking it.

**Comment by davidham** [comment]
Aha, I think I found it! I think the issue may be in [gulp_asset_helper.rb](https://github.com/vigetlabs/gulp-starter/blob/master/extras/rails/app/helpers/gulp_asset_helper.rb#L13). It's looking for 'public/' with a trailing slash, but the default in `config.json` is './public' (no trailing slash). Not finding that pattern, it just returns './public', which Rails doesn't know what to do with. When I added the slash to config.json, it started to work.

**Comment by greypants** [comment]
Were you running on port `8000` ? Or wherever you have browserSync set to run?

If you're feeling adventurous, I have a big update you can try out now that lets you install this as an npm dependency, and auto-generate all the rails extras you need to get running.

Assuming you've got a package.json file (otherwise run `npm init` first:
```
npm install --save-dev vigetlabs/gulp-starter#4.0.0-beta-2
node_modules/.bin/gulp-starter init-rails
```

**Comment by davidham** [comment]
I'm running Rails to 3000, so I set up BrowserSync to proxy to that, and I view it through port 3001. When I set up `config.json` to point to public-with-trailing-slash, it started to work:

```
"root": {
    "src": "./src",
    "dest": "./public/"
  }
```

I'm looking forward to v4, and in general this is way better for my needs than create-react-app, but I'll have to wait until next week or so to try it out--this week I gotta deliver features!

**Comment by greypants** [comment]
Thanks for the note on the trailing slash. I'll make sure that's working and included for v4

**Comment by davidham** [comment]
Sounds good. Thanks again for this project, really enjoying it.

**Comment by greypants** [comment]
Default rails config changed a bit, but should work. Lemme know if you have trouble getting set up with Blendid!

**Comment by amoshydra** [comment]
I am having problem with getting the app.js also

`yarn run blendid -- build` is able to produce the correct asset_path @ `localhost:3001/assets/gulp/javascripts/app.js`
However in development, the browser is expected the `app.js` from the same source also. However it is not available (404).

The `app.js` is however accessible from `localhost:3001/javascripts/app.js`

### `path-config.json`
```js
{
  "src": "./styleguide/src/assets/toolkit",
  "dest": "./public/assets/gulp",

  "javascripts": {
    "src": "../../../../gulpfile.js/assets/javascripts",
    "dest": "javascripts"
  }
  ...
```
