### ISSUE TITLE
critical inline css/js

### ISSUE THREAD

**Issue by simonpeters** [vigetlabs/blendid#335]
Hi,

I want to inline some critical CSS and JS from above the fold. Does anyone know how to add this to the current functionality?

**Comment by joemidi** [comment]
Could you not have CSS and JS blocks as shared elements in the HTML?

And just require those with nunjucks?

**Comment by simonpeters** [comment]
I wanted to use babel and sass so they have to go through the gulp pipeline. Doesn't look I can include files from the public folder into the html with nunjucks.

**Comment by joemidi** [comment]
hmm, maybe take a look at https://github.com/webpack/style-loader 


> Adds CSS to the DOM by injecting a `<style>` tag

**Comment by neutraltone** [comment]
For critical path CSS generation there are a number of tools which you can use to have this generated for you. Addy Osmani has a list of tools over at https://github.com/addyosmani/critical-path-css-tools

For JS, I'm not so sure.

**Comment by greypants** [comment]
You can now add [customTasks that run pre-build, post-build, and in development or production.](https://github.com/vigetlabs/blendid#additionaltasks)

You can also specifically [swap out the stylesheets task with an alternate task](https://github.com/vigetlabs/blendid#alternatetask).

**Comment by schellenbergk** [comment]
I'm having trouble figuring this out... @greypants , links you've posted no longer work... What I'm trying to do is to inline my entire app.css in Nunjucks in my layout template.  It has been half a year since this post, perhaps someone already figured it out by now.  Any help appreciated.. Thanks.
