### ISSUE TITLE
Font reference not updating in css file

### ISSUE THREAD

**Issue by AminulBD** [vigetlabs/blendid#346]
When I run the `gulp production` command with `"rev": true` in `config.json` file. In the CSS file, font URLs remains the same URL as before.

Check this image:
![error!](https://cloud.githubusercontent.com/assets/5006546/20421783/5aaae0bc-ad90-11e6-90ce-3c62847f45a6.png)

**Comment by greypants** [comment]
Font task is no-longer supported... though it still exists in the extras folder for reference.
