### ISSUE TITLE
Optional use of yml for data

### ISSUE THREAD

**Issue by cesasol** [vigetlabs/blendid#382]
THere are cases that it is needed long pieces of text as data in a project, and the yaml format makes it easier to handle large strings of text (like a blog post entry)

**Comment by greypants** [comment]
You can use the [dataFunction] config to customize this: https://github.com/vigetlabs/blendid#datafunction

**Comment by cesasol** [comment]
Great! It seems now that the most important thing for blendid right now is improve the documentation and examples with copy&paste snippets. I hope this weekend I can get into that
