### ISSUE TITLE
Craft init needs a public path?

### ISSUE THREAD

**Issue by gregkohn** [vigetlabs/blendid#432]
Looks like I needed to add:

```js
publicPath: "/assets/javascripts"
```

**Comment by mzlock** [comment]
@gregkohn Where did you need to add this, exactly?

**Comment by dipsynl** [comment]
I've also faced to this problem. In the task-config.js file you need to add:
`publicPath: '/assets/javascripts'`

to the javascript array. So it looks default like this way:
`
javascripts: {
    publicPath: '/assets/javascripts',
    entry: {
      app: ["./app.js"]
    }
  }
`
