### ISSUE TITLE
Importing jQuery for plugins with Webpack 2

### ISSUE THREAD

**Issue by hellojere** [vigetlabs/blendid#436]
Another newbie here with Webpack, so a little help would be appreciated. 

I found [this old issue](https://github.com/vigetlabs/blendid/issues/317) and do mostly understand what's behind the [Stackoverflow link](http://stackoverflow.com/a/28989476/484545) on that topic, but could someone kindly point out the preferred way on the current Blendid with Webpack 2 to achieve the following: 

```Javascript
var webpack = require("webpack");

    ...

    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery"
        })
    ]
```

Thanks already.

**Comment by greypants** [comment]
Ha... someone else just mentioned this in another issue. Here's the thread/answer: https://github.com/vigetlabs/blendid/issues/383#issuecomment-301474136

I'll beef up the docs on this.

**Comment by greypants** [comment]
You can also extend the webpack config with [customizewebpackconfig](https://github.com/vigetlabs/blendid#customizewebpackconfig)

**Comment by greypants** [comment]
Docs updated: https://github.com/vigetlabs/blendid#provide
