### ISSUE TITLE
yarn run blendid -- init-craft not creating correct directories

### ISSUE THREAD

**Issue by tommers-walker** [vigetlabs/blendid#441]
When I run 
`yarn run blendid -- init-craft`
the craft directories aren't being set up as described below:
![screen shot 2017-05-22 at 12 00 26](https://cloud.githubusercontent.com/assets/25368754/26305234/63064c3c-3ee6-11e7-80ac-e6d4aea5c026.png)

The only craft directory that gets created is the plugins folder..
Any ideas??

**Comment by greypants** [comment]
The task assumes you've already set up a basic Craft install. It doesn't install Craft itself.
