### ISSUE TITLE
Replace `gulp-gh-pages` with `gulp-gh-pages-cname`

### ISSUE THREAD

**Issue by dillonbailey** [vigetlabs/blendid#447]
https://github.com/shinnn/gulp-gh-pages doesn't provide support CNAME with github pages. This fork https://www.npmjs.com/package/gulp-gh-pages-cname nicely handles CNAME for github pages via the options object.

I didn't want this to be a slippery slope, but thought it may be handy with static hosting on the rise for applications. We didn't even realize it until today, but the gulp-gh-pages deploy task doesn't just not support CNAME, but will actually remove your CNAME from Github Pages during a deploy, which is a little dangerous...

**Comment by greypants** [comment]
Looks like switching packages isn't necessary... we just need to adjust the deploy task: https://github.com/shinnn/gulp-gh-pages/issues/105#issuecomment-266896331

Feel free to open a PR for that!

**Comment by dillonbailey** [comment]
@greypants awesome mate will do!

For PR do I just need to fork the repo and open a cross fork PR?

DB

**Comment by dillonbailey** [comment]
https://github.com/vigetlabs/blendid/pull/491

**Comment by dillonbailey** [comment]
Just learned that with latest blendid `^4.2.0` you just need to include a `CNAME` file in your `/src/static` folder with the desired custom URLs. 

Closing this off 🎉
