### ISSUE TITLE
Don't minify html in production

### ISSUE THREAD

**Issue by fmigliorato** [vigetlabs/blendid#472]
Is there a way to achieve that? I set "rev: false" in task-config.js but It's still minified

Thanks in advance

**Comment by CharlieGordon** [comment]
I have same problem

**Comment by dmitry-kuchura** [comment]
I have this question too

**Comment by cesasol** [comment]
The only way is to rewrite the html task, blendid offers the api for that

**Comment by lyuehh** [comment]
```
html: {
    htmlmin: false
  },
```

I add this to task-config.js, seems ok ..

**Comment by benjtinsley** [comment]
coming in late here but [html configuration options are defined here for future reference](https://github.com/vigetlabs/blendid/wiki/Configuration#html)
