### ISSUE TITLE
WordPress doesn't see js files in dev mode

### ISSUE THREAD

**Issue by Blinks44** [vigetlabs/blendid#479]
Hello! Thank you for such a great tool, but i have an issue with wordpress development.
In development mode wordpress doesn't see js files with this code
`wp_register_script( 'app.js', get_template_directory_uri() . '/dist/javascripts/app.js', '', '', true );`
But, it does after yarn run blendid -- build.

In dev mode i have to hardcode it in my footer.php to make it work and after development delete this code and build.
`<script src="/wp-content/themes/theme/dist/javascripts/app.js"></script>`

Any suggestions ? Thx!

**Comment by besimhu** [comment]
@Blinks44 it's because of hot module reloading. 

See our discussion on https://github.com/vigetlabs/blendid/issues/295

**Comment by greypants** [comment]
you want to use the `proxy` option of browserSync, and point it to your local wordpress url. https://browsersync.io/docs/options#option-proxy
