### ISSUE TITLE
yarn run blendid -- init error code 1

### ISSUE THREAD

**Issue by Corviusx** [vigetlabs/blendid#480]
When i try to run blendid for the first time i got this error:

```
λ yarn run blendid -- init
yarn run v0.27.5
$ "C:\Users\Corvi\Sedona\node_modules\.bin\blendid" "init"
'C:\Users\Corvi\Sedona\node_modules\.bin\blendid" "init' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

yarn/gulp installed globally
node version 6.11.0
tried different pc - same.

**Comment by mralessio** [comment]
I get the same error with `yarn run blendid -- build`

**Comment by Corviusx** [comment]
Also this is on windows 10, when i use bash from ubuntu subsystem all work fine.

**Comment by rabarbara** [comment]
Node: v8.2.1   
Yarn: v0.27.5   
Windows 7

Same issue.

**Comment by DmitryScaletta** [comment]
Same issue.
But this one works well: `./node_modules/.bin/blendid.cmd -- build`

**Comment by trickydisco78** [comment]
I don't get an error but none of the commands passed to blendid work (-- init or --build) it runs the default server every time

Win7
node 6.10.1
yarn 0.27.5

**Comment by neuotq** [comment]
```
Node: v8.2.1
Yarn: v0.27.5
gulp: v3.9.1
Windows 10
```
BTW it can be yarn or gulp bug, after we put command `yarn run blendid -- init` it converts it to `"C:\blahblah\node_modules\.bin\blendid" "init"`, windows try to run "init" as separate command and cant find it.
 If yarn convert it to `"C:\blahblah\node_modules\.bin\blendid init"` or `"C:\blahblah\node_modules\.bin\blendid" init` all will be fine.

**Comment by neuotq** [comment]
Just for now we can modify recomendations from readme, and use this Yarn scripts.
Add them to **package.json**

```
"scripts": {
    "start": "yarn run blendid",
    "build": "./node_modules/.bin/blendid build"
  }
```
After this, you can run `yarn start` to start blendid dev enviroment, `yarn run build` to build project.

**Comment by benjtinsley** [comment]
@Corviusx it appears @neuotq worked for you. unless there are other issues, i will close out this issue
