### ISSUE TITLE
How to use import modules to use in additionalTasks?

### ISSUE THREAD

**Issue by york-xtrem** [vigetlabs/blendid#486]
For example "gulp-imagemin":

```javascript 
// task-config.js
additionalTasks: {
    initialize(gulp, PATH_CONFIG, TASK_CONFIG) {
      gulp.task('compressImages', function () {
        return gulp.src(PATH_CONFIG.images.src)
          .pipe($.imagemin({
            progressive: true,
            interlaced: true
          }))
          .pipe(gulp.dest(PATH_CONFIG.dest + PATH_CONFIG.images.dest)));
      })
    },
    development: {
      prebuild: [],
      postbuild: []
    },
    production: {
      prebuild: [],
      postbuild: ['compressImages']
    }
  }
```

**Comment by dillonbailey** [comment]
@york-xtrem not sure if this will be useful, but...take a look at the top of this GIST

https://gist.github.com/dillonbailey/c06b1ee88ab1432435515c65840daf74

1. `yarn add gulp-imagemin -D`
2. Declare `const imagemin = require('gulp-imagemin');` at the top of your `task-config.js`
3. Should all work

Not sure why you are referencing `$` in your snippet but you would need to import that as well if imagemin needs it.

**Comment by york-xtrem** [comment]
Thanks @dillonbailey !  I will try that.

**Comment by benjtinsley** [comment]
@york-xtrem did the solution provided by @dillonbailey suffice? i will close this out unless there are further issues you may be having
