### ISSUE TITLE
Watch PHP files?

### ISSUE THREAD

**Issue by robbymilo** [vigetlabs/blendid#510]
Is it possible to configure webpack and browsersync to watch and update PHP files?

**Comment by HJ-b** [comment]
In your config file you can set the ‘files’ option to tell browserSync to watch additional files.

Check the  browsersync secrion in the readme file for an example.

**Comment by nikosolihin** [comment]
But this just refreshes the browser and doesn't seem to execute the tasks defined through additionalTasks
