### ISSUE TITLE
drop gulp-util dependency

### ISSUE THREAD

**Issue by olets** [vigetlabs/blendid#516]
gulp-util is now deprecated. All of its features have been broken out into standalone plugins, which should be used in place of gulp-util.

Documentation for how to transition is at https://github.com/gulpjs/gulp-util

**Comment by dillonbailey** [comment]
@olets I've just taken the time this morning to remove `gulp-util` and replace where necessary with the recommended packages from https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

Will create a pull request if you wanted to include before 5.0
