### ISSUE TITLE
Yarn & NPM not pulling latest version

### ISSUE THREAD

**Issue by splicebison** [vigetlabs/blendid#525]
When using yarn add, I get v4.3.1 however the code is outdated somehow. I've tried multiple node/npm/yarn versions as well as clearing yarn cache. I need the newer version of gulpfile.js > tasks > browserSync.js to inject the connect-history-api-fallback into the new extraMiddlewares prop provided in the latest version. Any thoughts on this?

**Comment by benjtinsley** [comment]
@splicebison thanks for submitting. how do you know the code is outdated?

**Comment by splicebison** [comment]
@benjtinsley Viewing file node_modules > blendid > gulpfile.js > tasks > browserSync.js.

**Comment by splicebison** [comment]
Ok, please do let me now. I'm using the Raw file pasted into the node_module at the moment in anticipation (time constraints). Thanks.

**Comment by maoueh** [comment]
I just did:

```
$ mkdir /tmp/blendid-test && cd /tmp/blendid-test
$ yarn init -y
$ yarn add --dev blendid

$ grep version node_modules/blendid/package.json
  "version": "4.4.1",
```

The `node_modules > blendid > gulpfile.js > tasks > browserSync.js` seems ok also. Resolved?

**Comment by splicebison** [comment]
@maoueh Tested and working. Latest 4.4.1 pulls correct files. Thanks. Closing issue.
