### ISSUE TITLE
Blendid init seems to not work correctly on latest version (4.4.1)

### ISSUE THREAD

**Issue by maoueh** [vigetlabs/blendid#527]
```
$ mkdir /tmp/blendid-test && cd /tmp/blendid-test
$ yarn init -y
$ yarn add --dev blendid
# Note that in latest Yarn version, the `--` is not required, `README.md` should be updated
$ yarn run blendid -- init 
yarn run v1.4.0

$ /private/tmp/blendid-test/node_modules/.bin/blendid init
[09:35:33] Working directory changed to /private/tmp/blendid-test/node_modules/blendid/gulpfile.js
[09:35:35] Using gulpfile /private/tmp/blendid-test/node_modules/blendid/gulpfile.js/index.js
[09:35:35] Starting 'init'...
[09:35:35] Generating default Blendid project files

To start the dev server:

yarn run blendid

[09:35:35] Finished 'init' after 16 ms
✨  Done in 3.05s.

$ ls
node_modules package.json yarn.lock
```

Not sure what's wrong however. Specific to my machine? If someone could try on their end, would be appreciated :)

**Comment by kferran** [comment]
Running into a similar issue when trying to run `yarn run blendid`.
![image](https://user-images.githubusercontent.com/46829/35053400-3ba275ec-fb67-11e7-9e46-edb674afe712.png)

Issue seems to show up in version 4.4.0 as well. I reverted back to version 4.3.1

**Comment by maoueh** [comment]
High chances it's not related to the `init` behavior problem described in this issue. Can you open a new issue?

**Comment by benjtinsley** [comment]
i encountered this yesterday and seemingly related to `gulp.dest` `merge-streams` or something else entirely. i'll take a crack at this and hopefully have something soon, in the meantime @kferran 's solution is the best for anyone else with this problem: **install version `4.3.1` to ensure your new projects succeed**

**Comment by benjtinsley** [comment]
@maoueh @kferran i released 4.4.2 which addresses this. if you encounter any other problems, let me know!

**Comment by maoueh** [comment]
@benjtinsley I confirm `init` works again with `4.4.2`. But @kferran should confirm for his own use case as I really think his problem is unrelated to the `init` problem. We will know soon :)

**Comment by kferran** [comment]
Still running into the same issue on my end after upgrading to version `4.4.2`.
http://prntscr.com/i2drtz

**Comment by maoueh** [comment]
@kferran Please open a new issue so we can track there. It might be related to windows. I have a Windows machine at home, if I have time, I will try to test it here. I'm wondering if my `bin` fix (#471) might be the culprit here.

**Comment by benjtinsley** [comment]
interesting. @kferran when you run `yarn run blendid -- init` or `yarn run blendid` you are doing so from the `kferran\website\app\` directory? it is strange that it is looking for the `package.json` file within `node_modules\`

**Comment by benjtinsley** [comment]
yes what @maoueh i think we can track this better in its own issue

**Comment by kferran** [comment]
I will open a new issue, but yeah I am running it from the app directory.

**Comment by kferran** [comment]
Moved the issue I am having to #532
