### ISSUE TITLE
blendid > 4.4.0 does not build src/ or config/ directories on initialize

### ISSUE THREAD

**Issue by benjtinsley** [vigetlabs/blendid#530]
seemingly not a problem for folks upgrading from existing versions, but definitely a problem on new builds. without the correct directories, all other tasks fail without the appropriate src files to reference.

**Comment by maoueh** [comment]
@benjtinsley Seems the same as #527 I just reported. Do you want me to close it?

**Comment by benjtinsley** [comment]
@maoueh ah perfect, no we can close this one. thanks for reporting. i'll have a look and hopefully close it out soon. in the meantime, use version 4.3.1 to ensure new builds work as expected
