### ISSUE TITLE
nunjucks

### ISSUE THREAD

**Issue by mhardaniel123** [vigetlabs/blendid#560]
how to use nunjucks? thanks..

**Comment by yannou788** [comment]
Hello you can find the Nunjucks documentation here https://mozilla.github.io/nunjucks/ it's like twig syntax if you already know twig

**Comment by mhardaniel123** [comment]
can i use it to load ajax data?

**Comment by yannou788** [comment]
Nunjucks is a templating engine that facilitate your template development. You can set (example) a **Koa** Server with **Nunjucks**.  **Koa** will give you the possibility to fetch and pass the ajax data to your template. Or you can just use a Javascript Ajax query.

**Comment by mhardaniel123** [comment]
i used ajax query but how should i loop my data on template?

`function loadUser() {
  $.ajax({
    method: "GET",
    url: "https://api-dashboard.test/portfolios/testing",
    contentType: "application/json",
    dataType: "json",
    success: function(data) {
      console.log(data.data, "data");
      var data = data.data;
    },
    error: function(jqXhr, json, errorThrown) {}
  });`

**Comment by yannou788** [comment]
If you want do that, i suggest you to use expressjs server or other.

You will have a code like that (example) : 

```javascripts 'use strict';

var path = require('path');
var nunjucks = require('nunjucks');
var express = require('express');
const fetch = require('node-fetch')
const PORT = process.env.PORT || 3000

function get(url) {
  return new Promise((resolve, reject) => {
    fetch(url)
      .then(res => res.json())
      .then(data => resolve(data))
      .catch(err => reject(err))
  })
}

var app = express();
nunjucks.configure(path.join(__dirname, 'views'), {
  autoescape: true,
  express: app,
  watch: true
});

// app

app.use(express.static(__dirname));

app.get('/', function(req, res) {
  Promise.all([
    get(`https://api-dashboard.test/portfolios/testing`)
  ])
  .then(([data]) => res.render('index.html', data.data))
  .catch(err => res.send('Something has gone wrong'))
});
