### ISSUE TITLE
The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by toporan** [vigetlabs/blendid#587]
While trying to install, I get lots of warnings and then, at the very end, I get this fatal error

error blendid@4.5.2: The engine "node" is incompatible with this module. Expected version ">=6.11.1 <10". Got "10.16.3"
error Found incompatible module.

**Comment by brian-g** [comment]
Adding --ignore-engines to `yarn install` will bypass the problem.

**Comment by toporan** [comment]
OK, it worked.
For any other having this issue, the command is:

**yarn add blendid --ignore-engines**

There is no yarn install! :-)

**Comment by levonter** [comment]
exactly looking for this
